file_mapping = {
    '..\\all_items_long_list\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente - Lange Liste',
    '..\\all_items_short_list\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente',
    '..\\all_items_short_list_BERT_base\\eval': 'bert-base-uncased mit Nutzung aller Listenelemente',
    '..\\all_items_short_list_EL\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und Entity Linking',
    '..\\all_items_short_list_EL_candidate_list\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente, Entity Linking und Kandidatenliste',
    '..\\all_items_short_list_NO_EL_candidate_list\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und Kandidatenliste',
    '..\\first_item\\eval': 'distilbert-base-uncased mit Nutzung des ersten Listenelements aus dem Goldstandard',
    '..\\first_item_EL\\eval': 'distilbert-base-uncased mit Nutzung des ersten Listenelements aus dem Goldstandard und Entity Linking',
    '..\\mapped_to_numbers\\eval': 'distilbert-base-uncased mit Mapping des Goldstandards auf Zahlen',
    '..\\ENHANC_namespace_mapping\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und Namespace Mapping',
    '..\\ENHANC_guaranteed_output\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und garantierter Vorhersage',
    '..\\ENHANC_guarantedd_output_namespace_mapping\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente, Namespace Mapping und garantierter Vorhersage',
    '..\\ENHANC_3_items_output\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und 3 Items als garantierte Vorhersage',
    '..\\ENHANC_5_items_output\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und 5 Items als garantierte Vorhersage',
    '..\\ENHANC_10_items_output\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und 10 Items als garantierte Vorhersage',
    '..\\GPT2_all_items_short_list\\eval': 'gpt2 mit Nutzung aller Listenelemente',
    '..\\GPT2_3_items_output\\eval': 'gpt2 mit Nutzung aller Listenelemente und 3 Items als garantierte Vorhersage',
    '..\\GPT2_5_items_output\\eval': 'gpt2 mit Nutzung aller Listenelemente und 5 Items als garantierte Vorhersage',
    '..\\GPT2_10_items_output\\eval': 'gpt2 mit Nutzung aller Listenelemente und 10 Items als garantierte Vorhersage',
    '..\\GPT2_guaranteed_output\\eval': 'gpt2 mit Nutzung aller Listenelemente und garantierter Vorhersage',
    '..\\ENHANC_confidence_value_-1\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und einem Schwellenwert von -1',
    '..\\ENHANC_confidence_value_-2\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und einem Schwellenwert von -2',
    '..\\ENHANC_confidence_value_-3\\eval': 'distilbert-base-uncased mit Nutzung aller Listenelemente und einem Schwellenwert von -3',
}
